# bhagavad_gita_quotes.py

bhagavad_gita_quotes = {
    1: "You have the right to work, but never to the fruit of work.",
    2: "Change is the law of the universe. You can be a millionaire, or a pauper in an instant.",
    3: "The mind is restless and difficult to restrain, but it is subdued by practice.",
    4: "A person can rise through the efforts of his own mind; or draw himself down, in the same manner.",
    5: "When meditation is mastered, the mind is unwavering like the flame of a lamp in a windless place.",
    6: "The soul is neither born, and nor does it die.",
    7: "You came empty handed, and you will leave empty handed.",
    8: "He who has no attachments can really love others, for his love is pure and divine.",
    9: "The soul is eternal and imperishable.",
    10: "A man is made by his belief. As he believes, so he is.",
    11: "Self-control is the key to success.",
    12: "The more one does, the more one has.",
    13: "The one who is not disturbed by the dualities of happiness and distress is certainly eligible for liberation.",
    14: "To be able to control the mind is a great achievement.",
    15: "The universe is not outside of you. Look inside yourself; everything that you want, you already are.",
    16: "There is neither this world, nor the world beyond, nor happiness for the one who doubts.",
    17: "When the mind is in control, it becomes the best of friends. When it is out of control, it becomes the worst of enemies.",
    18: "The wise, seeing the same God in all beings, see the same in everyone.",
    19: "In the presence of the wise, one should conduct oneself with humility.",
    20: "Knowledge is the ultimate source of power.",
    21: "No one can be happy without being free.",
    22: "When the mind is unsteady, wisdom cannot flourish.",
    23: "As the fire consumes wood, so does the fire of wisdom consume all reactions.",
    24: "Work is a means of purification.",
    25: "The best way to find yourself is to lose yourself in the service of others.",
    26: "He who is unattached to external activities, who is free from all dualities, is really free.",
    27: "Your work is to discover your world and then with all your heart give yourself to it.",
    28: "Desire is a constant source of suffering.",
    29: "Surrender to the divine will brings peace and liberation.",
    30: "Happiness is a state of mind.",
    31: "The ultimate aim of life is to realize the self.",
    32: "A person who is not disturbed by the external world remains in perfect peace.",
    33: "The greatest glory in living lies not in never falling, but in rising every time we fall.",
    34: "Your actions should be driven by your higher self.",
    35: "Be steadfast in yoga, O Arjuna. Perform your duty and abandon all attachment to success or failure.",
    36: "It is better to do your own duty imperfectly than to master the duty of another.",
    37: "The one who is devoted to me, and who is always thinking of me, will be freed from all material desires.",
    38: "Yoga is the journey of the self, through the self, to the self.",
    39: "Fearlessness is the first requisite of spirituality.",
    40: "Let your mind be set on the divine, and all your actions will be infused with the divine spirit.",
    41: "What is night for all beings is the time of awakening for the sage.",
    42: "He who is not disturbed by the dualities of life can attain eternal peace.",
    43: "The wise see the same in friend and foe.",
    44: "In the end, the soul will triumph over all adversity.",
    45: "The wise should have compassion for all beings.",
    46: "Even the smallest of deeds is better than the greatest of intentions.",
    47: "He who has conquered himself is greater than he who has conquered a thousand men.",
    48: "In every crisis, there is a possibility for growth.",
    49: "Happiness is a journey, not a destination.",
    50: "One should not be discouraged by failure; rather, learn from it.",
    51: "As a man thinks, so he becomes.",
    52: "Peace comes from within. Do not seek it without.",
    53: "Success is not the key to happiness. Happiness is the key to success.",
    54: "When the body dies, the soul is eternal.",
    55: "Strength does not come from physical capacity. It comes from an indomitable will.",
    56: "True knowledge is that which leads to liberation.",
    57: "Act without attachment to the fruits of your labor.",
    58: "By selfless service, one can attain the supreme state of bliss.",
    59: "To control the mind is the greatest achievement.",
    60: "He who has faith has everything.",
    61: "The soul is beyond birth and death.",
    62: "Love is the greatest power in the universe.",
    63: "One who is devoted to the self sees all beings in the self.",
    64: "When you give up attachment, you attain liberation.",
    65: "Your faith determines your experience.",
    66: "Life is a challenge; meet it.",
    67: "You are what you believe yourself to be.",
    68: "The true purpose of life is to find God within.",
    69: "The essence of all beings is the same.",
    70: "Wisdom is knowing how to do it.",
    71: "A disciplined mind leads to success.",
    72: "You cannot always control what goes on outside, but you can control what goes on inside.",
    73: "Strength does not come from winning. Your struggles develop your strengths.",
    74: "Live as if you were to die tomorrow. Learn as if you were to live forever.",
    75: "The mind is everything. What you think you become.",
    76: "Every action is a reflection of your thoughts.",
    77: "Forgive others, not because they deserve forgiveness, but because you deserve peace.",
    78: "Doubt is the thief of joy.",
    79: "Peace is the ultimate goal of all beings.",
    80: "He who is content is rich.",
    81: "There is no greater happiness than peace of mind.",
    82: "Cultivate an attitude of gratitude.",
    83: "Your mind is a garden. Your thoughts are the seeds.",
    84: "You have the power to change your story.",
    85: "Surrender to the divine plan, and all will be well.",
    86: "Your heart is the compass guiding you.",
    87: "Love and compassion are necessities, not luxuries.",
    88: "True strength is keeping everything together when everyone expects you to fall apart.",
    89: "Live simply, dream big.",
    90: "The path is long, but the destination is worth it.",
    91: "Believe in yourself and all that you are.",
    92: "Life is a series of choices. Make them wisely.",
    93: "You are not a drop in the ocean. You are the entire ocean in a drop.",
    94: "Mindfulness is the key to inner peace.",
    95: "In the midst of movement and chaos, keep stillness inside of you.",
    96: "Whatever you do, do it with all your heart.",
    97: "Kindness is a language which the deaf can hear and the blind can see.",
    98: "In every encounter, there is a lesson to learn.",
    99: "Be the change you wish to see in the world.",
    100: "True wisdom is knowing what to ignore."
}
